### ISSUE TITLE
Node 0.6.* support

### ISSUE THREAD

**Issue by quangv** [wright-io/givenwhenthen#3]
hello there!  Brilliant project, I'm anxious to try it out.

I'm currently running node 0.6.5 , I'm having some difficulty starting it.

```
[~/ssh/repos/givenwhenthen/examples]$ cake test:acceptance

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:376:11)
    at Object.<anonymous> (/home/quang/ssh/repos/open.core/lib/src/open.server/config/paths.coffee:25:17)
    at Object.<anonymous> (/home/quang/ssh/repos/open.core/lib/src/open.server/config/paths.coffee:29:4)
    at Module._compile (module.js:432:26)
    at Object..coffee (/home/quang/ssh/repos/open.core/node_modules/coffee-script/lib/coffee-script/coffee-script.js:21:21)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at /home/quang/ssh/repos/open.core/lib/src/open.server/index.coffee:89:18
```

cheers,
Quang

**Comment by quangv** [comment]
okay, so I got it working... (note I changed open.core dependency of express from 2.4.0 to \* beforehand so `npm install` would work)

I commented out the `require.paths` code in `open.core/lib/src/open.server/config/paths.coffee`
and added a `node_modules` directory in `open.core/lib/src` with a sym-link to _open.client_ and _open.server_

So the example test ran without a problem... now does GivenWhenThen only work with SauceLabs or can it support local Selenium server somehow?

Thanks,
Quang

**Comment by wright-io** [comment]
Beautiful, Quang!  Very happy to have you looking at the project!  GivenWhenThen is focused on SauceLabs right now, but it could fairly easily be modified to point at another remote Selenium instance (or local if you used remote protocols).

The current master uses Soda, which can be pointed to another URL in it's configuration.  This is done in acceptance.coffee - createBrowser.  A call to soda.createClient (instead of createSauceClient) would allow you to point at a different Selenium RC server.

However, there is a current pull request we will be merging very soon that makes a fairly big change and converts to use Selenium 2 and no longer uses Soda.  This is the direction we intend to go.  That means you'd need a local Selenium 2 instance.  Let me know if you're interested in this and we can talk about adding support for directly configuring the Selenium 2 RemoteWebDriver URL.  There are some special features of Sauce Labs being used that might have to be handled conditionally (see acceptance.coffee in wd branch), but other than that it's just a matter of making the URL and port configurable.

**Comment by quangv** [comment]
oh Soda doesn't support Selenium 2 ?

Yeh I'm def interested, GivenWhenThen looks awesome, but unfortunately I do not use SauceLabs currently...

**Comment by wright-io** [comment]
Correct - Soda doesn't support Se2.  If you want to play with GivenWhenThen immediately you can get a free SauceLabs account.  Or you can make the small Soda config change I suggested in acceptance.coffee as a temporary fix.

**Comment by quangv** [comment]
Okay, so I'm checking out SauceLabs now, so with Sauce Labs I don't need a _local Selenium 2 instance_?

What is that, is it `selenium-server-standalone-2.15.0.jar`? I'm currently using that with just the command `java -jar selenium-server-standalone-2.15.0.jar`

The new version of GivenWhenThen uses it's own custom driver instead of Soda? So currently it only works with SauceLabs, and with SauceLabs you wouldn't need to install Selenium sever standalone to use GivenWhenThen correct?

Thanks,

---

After entering my SauceLabs information, I still don't think it's working on 0.6.\* possibly, all I get is

```
[~/ssh/repos/givenwhenthen/examples]$ cake test:acceptance
The "sys" module is now called "util". It should have a similar interface.
Running 1 stories containing 1 scenarios against 2 browser/os configurations... 
. . 
Done
```

After changing _google_search_test.coffee_ to something that surely should fail, it still says `Done` in the results when running `cake test:acceptance`, and I see no-activity in my SauceLabs account... 

it might be cause of node 0.6.\* or something wrong with my setup...

**Comment by wright-io** [comment]
Quang,
  You are correct that with Sauce Labs you don't need local Selenium (e.g. `selenium-server-standalone-2.15.0.jar`) running.  It's cool because you can run against different operating systems and all major browser types and versions without having to install anything or maintain any infrastructure.

The new version of GWT does have its own driver.  It shouldn't be too hard to alter that driver to support local Selenium, but I would recommend checking out Sauce first because, if it meets your needs, it's so much easier to manage.

The error you are getting does look like a node version problem.  We'll have a look at it.

**Comment by quangv** [comment]
GWT = google web toolkit?

They have their own selenium driver that could work with GivenWhenThen (1.0) with Node?

**Comment by wright-io** [comment]
Sorry to be confusing.  I meant GWT = "GivenWhenThen".  I guess Google has the earlier use of the acronym :-).  GivenWhenThen has its own driver, which can be used with the GivenWhenThen DSL, or independently as a standalone driver.  It works easily with Sauce, so I would recommend starting there.  We do need to iron out the issues that you're having that look node version related though.

**Comment by wright-io** [comment]
Also wanted to let you know that 0.1.0 is released.  It may be worth checking it it resolves the errors you were seeing above.

**Comment by quangv** [comment]
cool, yeh I was able to get it working with 0.1.0 :) ... SauceLabs seems like it can be useful... I'd have to look more into it. Thanks!

**Comment by ghost** [comment]
Looks like this was fixed a while ago. Closing.
